version: '3.8'
services:
  nuxtNginx:
    image: nginx:1.23-alpine
    container_name: nuxtNginx
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
